### ISSUE TITLE
Please add awesome link

### ISSUE THREAD

**Issue by kimtth** [trackawesomelist/trackawesomelist-source#42]
https://github.com/kimtth/awesome-azure-openai-llm

```yml
  kimtth/awesome-azure-openai-llm:
    category: Learn
    default_branch: main
    files:
      README.md:
        index: true
```

        
Thank you in advance for your support
