### ISSUE TITLE
Add "Awesome Jetbrains Plugins" list

### ISSUE THREAD

**Issue by clutcher** [trackawesomelist/trackawesomelist-source#51]
Awesome list of plugins for Jetbrains IDEs: https://github.com/clutcher/awesome_jetbrains_plugins

```
clutcher/awesome_jetbrains_plugins:
  category: Editors
  default_branch: main
  files:
    README.md:
      index: true
```
